### ISSUE TITLE
SMS sometimes fails to be sent

### ISSUE THREAD

**Issue by phsultan** [voxbone/voxsms-npm#1]
Hi,

I have been trying multiple ways to send SMS to Voxbone from various Node.js endpoints, and none of them seems 100% reliable, including those packages:
- npm request 
- npm http-digest-client
- voxbone-voxsms

Both of them can send SMS most of the time, but failures occur too often (excerpt taken from the logs of voxbone-voxsms):

```
I20151201-10:55:28.403(1)? [DEBUG] An error occured while sending the SMS.
I20151201-10:55:28.403(1)? null
I20151201-10:55:28.403(1)? <html>
I20151201-10:55:28.403(1)? <head>
I20151201-10:55:28.404(1)? <title>Error 401 Unauthorized</title>
I20151201-10:55:28.404(1)? </head>
I20151201-10:55:28.404(1)? <body>
I20151201-10:55:28.404(1)? <h2>HTTP ERROR: 401</h2><pre>Unauthorized</pre>
I20151201-10:55:28.404(1)? <p>RequestURI=/sms/v1/33612536709</p>
I20151201-10:55:28.405(1)? <p><i><small><a href="http://jetty.mortbay.org">Powered by Jetty://</a></small></i></p>
I20151201-10:55:28.409(1)? </body>
I20151201-10:55:28.409(1)? </html>
```

The Digest authentication method is causing the problem for those Node.js packages, for some reason, the server refuses to authenticate some requests and resends 401 responses. Then, resending the request several times until it succeeds is necessary.

The problem never occurred when using cURL in a terminal.

**Comment by vmorsiani** [comment]
Hello,

After investigating this issue, I can confirm I'm able to reproduce it.
So here's an explanation about the issue:

voxsms.voxbone.com is load balanced between 2 nodes as shown in the nslookup below

```
$ nslookup sms.voxbone.com
Name:   sms.voxbone.com
Address: 81.201.83.10
Name:   sms.voxbone.com
Address: 81.201.82.10
```

I ran ngrep while using the node library and it seems like nodejs is not reusing tcp connection.
This causes the first request to sometime hit one of the sms node, get the nounce for the digest auth and then try to authenticate toward the second node.

Sometime, with a bit of luck, you get your http request directed twice to the same node and it ends up in a correct response.

On the flip side, curl is reusing the TCP connection, and this is why it always works.

To be honest, I don't have any idea on how to tackle this issue.
I'll have a look at this and see if I can find a solution, meanwhile the only thing I could see is that you use one of the node ip instead of the domain name.

**Comment by phsultan** [comment]
@vmorsiani thanks a lot, that gives us a nice workaround. You spotted the problem as Node.js uses several TCP connections to authenticate. I tried to set `maxSockets: 1` in the `request` module without luck and finally gave up.

However, we would like to use this package not to have to deal with fragmentation, but the host sms.voxbone.com cannot be modified (line 46):

```
sendSMSRequest('https://sms.voxbone.com:4443/sms/v1/'+to, data);
```

Would it be possible to add an argument to the `sendSMS` function to change the URL host ?

Thanks a lot for your valuable input !

**Comment by vmorsiani** [comment]
Hello,
I added the url parameter so you should be able to specify the ip of your choice.
Please note that by doing so, you'll have an issue with ssl certificates being declared invalid (as the certificates covers sms.voxbone.com domain name)

You can work around this by disabling the check as explained in the following stackoverflow post:
http://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request

From now on, I'll probably improve a bit the logging to report more info about errors before actually tagging the version

**Comment by phsultan** [comment]
Thanks a lot for the update @vmorsiani !

Could you please update the npm package there as well: https://www.npmjs.com/package/voxbone-voxsms 

Thanks again !

**Comment by sachanacar** [comment]
Thanks a lot for taking care of this @vmorsiani this is major dopeness! I've updated the package on the NPM public repo: https://www.npmjs.com/package/voxbone-voxsms

Thanks for reporting the issue @phsultan !

**Comment by vmorsiani** [comment]
Thanks Sacha, I'll close this issue then.
